# This config file is meant for settings that affect your whole blog, values which you are expected to set up once and rarely edit after that.
# Site settings---
#title of your website, as you want it to appear in the header of the website
title: Judaica DH at the Penn Libraries
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://judaicadh.github.io
baseurl:
email: judaicadh@gmail.com
# description for RSS feeds
description: Judaica Digital Humanities at the University of Pennsylvania Libraries
  features projects that connect the Judaic past to the technological present and
  future.
google_analytics: UA-88257588-1
people:
- name: Emily Esten
  category: current
  modal-id: emilyesten
  pic: estenheadshot
  position: Judaica Digital Humanities Coordinator
  bio: "Emily uses digital humanities methods to deepen public and scholarly engagement with our Judaica materials. She has been involved in a number of Digital Humanities projects, and was a 2016-2018 HASTAC Scholars Fellow. Before Penn, she worked at several museums and cultural heritage sites, including the Smithsonian Center for Learning and Digital Access, the Kennedey Institute for the United States Senate, and the New Bedford Whaling Museum. Emily holds a Master's Degree in public humanities from Brown University, and a Bachelor of Arts degree, with majors in history and digital humanities, from the University of Massachusetts Amherst."
  social:
  - title: twitter
- name: Laura Newman Eckstein
  category: alum
  modal-id: lauranewmaneckstein
  pic: ecksteinheadshot
  position: Inaugural Judaica Digital Humanities Coordinator
  bio: "Laura worked as the Judaica Digital Humanities Coordinator at the Penn Libraries from October 2016-June 2018. She left the position in order to pursue her PhD in Early Atlantic Jewish History at University of Pennsylvania. Laura holds a bachelor's degree with the highest honors in religion from Haverford
    College. Laura's senior thesis at Haverford focused on Jewish peddlers, their
    business networks, and their religious practices along the Lower Mississippi River
    between 1820-1865. Laura is the recipient of a 2014 Tri-College, Mellon Foundation
    Digital Humanities Fellowship where she where she worked with Professor Ryan Cordell
    in his lab for Viral Maps, Texts and Networks at Northeastern University, mapping
    the spread and reprinting of 19th century newspapers and magazines. Laura is also
    the recipient of a John B. Hurford Arts and Humanities Center Summer Research
    Fellowship."
  social:
  - title: twitter
- name: Laurie Allen
  category: alum
  modal-id: laurieallen
  pic: allenheadshot
  position: Director for Digital Scholarship
  bio: "Laurie is the Director for Digital Scholarship in the Penn Libraries, where
    she leads a group working to expand the capacity of researchers at Penn to create
    and share scholarship in new forms. The group engages in digital project development,
    data management and curation, mapping, experimentations with emerging research
    methods, and open access publishing. </br></br> Laurie has been involved in a
    number of Digital Humanities projects, including her work on Ticha: a digital
    text explorer for Colonial Zapotec and her role as Research Director for Monument
    Lab a public art and research project focused on 21st century memory practices
    in the city of Philadelphia. She holds a Bachelor''s degree in Philosophy from
    Bard College, and a Master''s of Library and Information Science from Simmons
    College."
  social:
  - title: twitter
- name: Arthur Kiron
  category: current
  modal-id: arthurkiron
  pic: kironheadshot
  position: Schottenstein-Jesselson Curator of Judaica Collections
  bio: 'Dr. Arthur Kiron is the Schottenstein-Jesselson Curator of Judaica Collections
    and Adjunct Assistant Professor of History at the University of Pennsylvania.
    He received his Ph.D. in Jewish history from Columbia University and also holds
    an M.A. in religious studies from Stanford University, where he focused on the
    history of Biblical interpretation. His B.A. is from Brandeis University, where
    he graduated magna cum laude in Political Theory and Women’s Studies and was the
    recipient of the Giller-Sagan Prize in Women’s Studies.</br></br>He currently
    oversees the Penn Library’s Judaica programs of education and outreach, such as
    exhibits, concerts, workshops, as well as national and international partnerships
    to digitize significant collections of Judaica.  He is the Director of the Jesselson-Kaplan
    American Genizah Project and is the editor of Constellations of Atlantic Jewish
    History: The Arnold and Deanne Kaplan Collection of Early American Judaica (2014),
    recipient of the Arline Custer Memorial Award. His academic scholarship mainly
    focuses on Atlantic Jewish history and the history of the Jewish book.</br></br>Arthur
    serves on numerous academic and communal advisory boards, including the Executive
    Committee of the Jewish Counter Culture Oral History Project, based at Penn; the
    Advisory Board of the Footprints provenance project, based at Columbia University,
    the Advisory Board of the Jewish Play Project, based at the Rochester Institute
    of Technology;  the International Advisory Board, Rabat Genizah Project;  Editorial
    Board, Association of Jewish Libraries; International Academic Advisory Board
    for Sephardic Studies/Livorno, Italy; the Academic Board of Advisors, American
    Jewish Historical Society;  Academic Advisory Board, Herbert D. Katz Center for
    Advanced Judaic Studies, University of Pennsylvania.'
  social:
  - title: twitter
#- name: Kim Eke
  #category: current
  #modal-id: kimeke
  #pic: ekeheadshot
  #position: Director for Digital Scholarship
  #bio: "Kim leads a team of library professionals that actively engage the Penn community in new library services designed to meet the changing needs of scholars. The Teaching, Research, and Learning Services team enables digital scholarship and multimodal research, open access publishing, technology-enhanced pedagogies, collection development, and interactive, experiential media production in support of Penn's mission. Kim provides strategic oversight for the campus learning management system serving 23,000 students daily and Penn's open access repository that hosts nearly 2.5 million downloads of scholarly content annually. TRL spans informal and formal learning spaces ranging from high-tech Commons spaces and active learning classrooms to the iconic Fisher Fine Arts and the Penn Museum Libraries. Learn more about current projects at penntrl.wordpress.com Before working at Penn, Kim managed enterprise-wide learning technologies, MOOC production, course design, and custom educational multimedia development at the University of North Carolina-Chapel Hill. Prior to UNC, Kim served in a variety of roles including instructional designer, faculty developer, instructor, media developer, and project manager/designer of online courses. She earned a Ph.D. in Environmental Resource Development from Michigan State University."
  #social:
  #- title: twitter
#we use social instead of twitter_username
social:
- title: twitter
  url: http://twitter.com/judaicadh
- title: github
  url: https://github.com/judaicadh
address:
- line: 3420 Walnut Street
- line: Philadelphia, PA 19104
markdown: kramdown
permalink: frontmatter
exclude:
- vendor
