source "https://rubygems.org"

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "3.5.0"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.0"

gem 'bundler', '~> 1.15.1'
# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.6"
   gem 'jekyll-seo-tag', '~> 2.3'
   gem 'jekyll-paginate', '~> 1.1'
   gem 'jekyll-sitemap', '~> 1.1', '>= 1.1.1'
   gem 'kramdown', '~> 1.14'
   gem 'rake', '~> 12.0'
   gem 'bigdecimal', '~> 1.3', '>= 1.3.2'
   gem 'jekyll-gist', '~> 1.4', '>= 1.4.1'
   gem 'jekyll-mentions', '~> 1.2'
   gem 'jekyll-assets', '~> 2.3', '>= 2.3.2'
   gem 'jekyll_search', '~> 0.0.8'
   gem 'bootstrap-sass', '~> 3.3.7'
	gem 'sass-rails', '>= 5.0.6'

   
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

